### ISSUE TITLE
Per-project/context RSS/iCal feeds show all todos

### ISSUE THREAD

**Issue by tedks** [TracksApp/tracks#1726]
This is the return of #1684, except text feeds are working. I can reproduce this on trunk by creating three tasks with three different projects, and requesting the feed for one project.

**Comment by dnrce** [comment]
@tedks, I'm not able to reproduce this following your instructions. Can you please confirm that you still see this issue, and perhaps provide more detail on reproducing it? Thanks!

**Comment by dnrce** [comment]
Scratch that, I see it.

**Comment by lrbalt** [comment]
I have tried to reproduce this, but I cannot. Both rss and txt work with a new db with one context, one project and two todos

**Comment by dnrce** [comment]
@lrbalt, try adding a second context. If you try to view the feed for one context, you will see the todos for all contexts.

**Comment by dnrce** [comment]
I see this with MySQL, too.

**Comment by dnrce** [comment]
This is apparently a really old bug. I'm trying to do a git bisect, but I've gone back to March 2013 and I haven't found a good commit yet.

Given its age, I don't think this should block 2.3.

**Comment by dnrce** [comment]
This seems to be an issue all the way back to 63175c115b9e9e9e740375e1edc99403b65094fc when these feeds were introduced.

**Comment by nav-star** [comment]
Last night I've upgraded my TRACKS installation from 1.7.2 to 2.3. With the corresponding db migration.
For my unpleasant surprise I've stumble upon this bug where the RSS  and iCal feeds  can not be context filtered (all the todos for all the contexts are displayed). The plain text feed is OK though. That's really annoying. And it feels like pretty trivial problem - seems like a "where" clause is missing in a select statement or something like this. But because of my shallow understanding of ruby/rails - I can not even find in the sources where the sqlite3 data extraction takes place for representing it in the three feeds formats.

Can't we just compare the working code in 1.7.2 and use it in 2.3? Can someone help me out here?
I can see this reference from dnrc, but can't really see where exactly the mistake is--> https://github.com/TracksApp/tracks/commit/63175c115b9e9e9e740375e1edc99403b65094fc

Thank you!

**Comment by C-Otto** [comment]
https://github.com/TracksApp/tracks/blob/master/app/views/todos/index.ics.erb#L11
https://github.com/TracksApp/tracks/blob/master/app/views/todos/index.rss.builder#L10

Those should reference `@not_done_todos` instead of `@todos`, which is correctly done for TXT feeds.

The computation in the controller seems to be alright, but the passing of local variables and the confusing name is not really what I consider perfect :)

**Comment by nav-star** [comment]
Great! Thanks man! That was fast. I was mistaken - not all contexts, but all todos (not only the incomplete ones)  from a context were shown. Now changing  @todos -->  @not_done_todos  in the corresponding line of index.ics.erb solved the problem for me.

Thanks once again!
