### ISSUE TITLE
Default context and tag for action broken after upgrade to 2.3.0

### ISSUE THREAD

**Issue by habernal** [TracksApp/tracks#1898]
I've upgraded from 2.2.3 to 2.3.0; when creating a new action and selecting existing project from the pop-up, the default tag and context are not filled automatically any more. No change in OS/browser/etc.

**Comment by habernal** [comment]
It's been over two years now with no update - is the project dead by now? I've seen some pull-requests merged but it doesn't look like active development. It would be really pity, the project is great!

**Comment by mattr-** [comment]
It's definitely in a sort of 'no man's land' at the moment. I know my personal system, part of which was Tracks, has gone completely out the window as I try to find something that works better for me with less friction. All of that to say that because I'm not using it at the moment, I'm also not spending a lot of time working on it.

So, it's not dead yet. I'll make a better effort to find more contributors within the next six months or so. Depending on what happens with that will determine whether or not it stays alive or dies off completely.

**Comment by habernal** [comment]
Sounds promising. By the way - what is the alternative that you're using?

**Comment by mattr-** [comment]
I'm not currently using GTD at all right now. I'm just writing stuff down with pen and paper and it feels less than optimal but it's very friction free since I keep a notebook and writing utensils on my desk all the time.
