### ISSUE TITLE
Modernize the testing infrastructure

### ISSUE THREAD

**Issue by mattr-** [TracksApp/tracks#1944]
I can appreciate the cucumber suite, but locally, on my machine, it renders Firefox useless for me because the webdriver takes complete control of a firefox window.

Let's work on switching to PhantomJS, perhaps with poltergeist or some other such thing that makes sense for what we're trying to do.

**Comment by dnrce** [comment]
How do you feel about RSpec vs MiniTest these days?

**Comment by mattr-** [comment]
I generally default to RSpec because it feels easier to describe test
scenarios with it and I know it better, so I don't fumble around with it as
much. However, I really don't have a strong opinion either way.

**Comment by mattr-** [comment]
This is moving higher up my priority list since the cucumber suite takes at least 75 minutes to run on my machine if I'm doing other things with the machine, and I didn't even let it finish.

**Comment by C-Otto** [comment]
I let it run in a virtual screen (vncserver). This makes the tests invisible, but of course they are not faster because of this.

**Comment by dnrce** [comment]
Yuck.

The real problem is that we have too many tests using Capybara to catch small edge cases. More of these should be captured in true unit tests.

My vote is to move to RSpec (with Capybara where necessary) across the board, and drop both Cucumber and MiniTest. Obviously that would be a substantial change but I have taken stabs at doing pieces of it and it's not terrible. Thoughts?

**Comment by mattr-** [comment]
I'm not sure what caused the test suite to take 75 minutes on my machine before, but I have it consistently running in 20 to 21 minutes now. That means it's moved down my priority list a bit as well.

I'd be onboard with rspec and capybara across the board.

**Comment by ZeiP** [comment]
This issue seems no longer relevant, closing.
