### ISSUE TITLE
[master] New layout: Move "Home" to the left

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1947]
With the very recent design changes the top menu shows the date, then "Home", "Starred", ...

I am used to having the "Home" button on the left. This is what is used on most websites (including Github).

Could you discuss reverting/adapting the change?

**Comment by mattr-** [comment]
The new nav bar on top is still a WIP. I would imagine there will be more changes, but I don't know what those will be yet. The prior layout worked because the count and date were on top of the 'Home' menu item. 

There are a few other things about the new nav that need to be addressed as well, like the position of the flash notification.

IOW, don't worry, we're nowhere near a release and we'll get it fixed. :smiley:
