### ISSUE TITLE
master: search bar not shown on mobile

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1949]
On my mobile phone, I can click the search icon in the menu bar, but on the site loaded after that I don't see any form which I could use to actually define my search. Google Chrome, Android. On my "big" computer (also Google Chrome) this is not an issue.

Can you reproduce this?

**Comment by mattr-** [comment]
If you visit `/search` manually on your phone, does it work?

**Comment by mattr-** [comment]
Ok, i was able to reproduce this on my phone. For some reason, the navbar doesn't condense with the smaller screen size.

Since this works with the desktop browser, I'm inclined to think that there's something about the way that tracks is handling the mobile request that is making the media queries in bootstrap that handle this fail to work.

**Comment by C-Otto** [comment]
@mattr- I can reproduce this by using a very narrow Desktop browser window (Chrome).

This is just a special case of #1952.
