### ISSUE TITLE
Failing cucumber tests

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1962]
Currently the cucumber tests (mostly for the "dependencies" feature) fail. I don't know if these failures are valid, but they need to be fixed anyway.

**Comment by mattr-** [comment]
I thought I had fixed these at one point, but I'll take a look again.

**Comment by mattr-** [comment]
Running through the cucumber tests when merging a prior PR, I got zero failures locally. We have always had problems with Travis and the dependency cucumber features. Since it's not a failure that I can reproduce locally, it makes it hard to fix, and so I'm going to punt on it for now, especially since I'm mucking about with the test suites nowadays anyways.
