### ISSUE TITLE
install instructions - migrations do not work and rails server wants docker-compose

### ISSUE THREAD

**Issue by benwilliams** [TracksApp/tracks#2170]
Following the install instructions, the migrations did not work until I changed these

-class CreateTracksDb < ActiveRecord::Migration
+class CreateTracksDb < ActiveRecord::Migration[5.2]

Then trying to start rails server, it complains about missing docker-compose.

**Comment by mattr-** [comment]
Thanks for opening this. The install instructions are meant for the most current release and aren't updated to work with the `master` branch yet. I'll update them before release.

**Comment by srbaker** [comment]
Heya, I'm running into similar. I have a bunch of hacking I want to do on Tracks, but its dependency on Docker is really putting me off. It's such a beautifully simple application, so if the docker dependency can be made "more optional" it would be lovely.

I'll even do the work, if you let me know how you'd like it done.

**Comment by mattr-** [comment]
@srbaker Are you on a platform that makes Docker harder to use? I was trying to make working on this project easier by using Docker and docker-compose so that things would be more normalized.

I'll approve and merge a PR that looks for a specially named dotfile and skips the docker set up if it's found. As long as I can continue using Docker by default, I'm happy to be accommodating to whatever other folks want. :smiley:

**Comment by srbaker** [comment]
Thanks, I'll look into this.

I don't think I'm on a platform that makes Docker harder to use, it just doesn't mesh with how I would like to work.

**Comment by ZeiP** [comment]
Ah. It seems we didn't update the install instructions to cover Docker, this should probably be done quite soon.

**Comment by boert** [comment]
`touch .skip-docker`
will help

**Comment by sccarr** [comment]
hi, any updates on this?  at the 
`bundle exec rails server -e production`
step, I get
`/Users/me/tracks/bin/../script/docker-environment: line 17: exec: docker-compose: not found`
but I am running Mac Mojave and Docker Compose should be included with Docker for OS.  But when I run 
```
me:tracks me$ docker --version && docker-compose --version
Docker version 19.03.8, build afacb8b
-bash: docker-compose: command not found
```
it makes me think Docker Compose is not installed.  I cannot figure out how to install it because every guidance I find assures me it should already be installed.  Would love to see some instructions on the Trax upgrade that cover Docker. 
thanks!!

**Comment by tet3** [comment]
@sccarr I'm not working on macOS, but on both windows and Linux `docker-compose` is installed separately from docker. Did you try `$ brew install docker-compose`?

**Comment by mattr-** [comment]
The way to avoid Docker is to create a `.skip-docker` file in the root of your tracks installation. On unix systems (macOS/Linux), this can be done with `touch .skip-docker`. I'm afraid I don't know the exact steps to do this if you're running on Windows. 

Once you do that, the existing [installation instructions](https://github.com/TracksApp/tracks/blob/master/doc/installation.md) should be sufficient to get things running. If they are not, please help us out by editing them and submitting a pull request if you had to take different steps.

**Comment by ZeiP** [comment]
There are now better installation instructions for the master branch in https://github.com/TracksApp/tracks/blob/master/doc/installation.md. I'm planning on releasing a new version after getting at least the library updates in, but it'd be awesome to have some feedback before the release.

I shifted the logic so that now you don't need to add the .skip-docker file (although it doesn't certainly harm any), but if you want to run commands and have them being run inside the Docker Compose installation you need to create a .use-docker file similarly.

There are updated instructions for using the Docker machines in the doc directory: https://github.com/TracksApp/tracks/blob/master/doc/installation.md  Let me know if you encounter any problems with them by posting a new issue. Thanks!
