### ISSUE TITLE
Is the IRC channel still the place to discuss Tracks development?

### ISSUE THREAD

**Issue by srbaker** [TracksApp/tracks#2217]
Sorry for putting this here. I'm not sure where the best place for discussions about new features is. Is anyone actively watching the IRC channel, or is there some place new?

I have a vague idea about some workflows for Capture / Inbox, and I'd like to get a feel from others about how they should look.

Cheers!

**Comment by srbaker** [comment]
I've joined the Gitter as well. :D

**Comment by mattr-** [comment]
I haven't been on the IRC channel in ages. The best thing to do really is to file an issue. 🙂 

I pop up on the Gitter occasionally, but with the low amount of activity both there and within the rest of the project as a whole, I tend to not be there often. 

Gonna close this one since I answered the question. Thanks for asking!
