### ISSUE TITLE
Remove database.yml from VCS

### ISSUE THREAD

**Issue by ZeiP** [TracksApp/tracks#2248]
Because I've configured my own database credentials in the software, config/database.yml is constantly showing as changed. It'd be better to remove it and have just the database.yml.tmpl that is already there.
Apparently there's some issue with the testing framework needing the database.yml file, could it be scripted around somehow?

**Comment by mattr-** [comment]
I'd rather do it the other way around and remove the template and keep the normal `config/database.yml` checked in. If you're using the docker setup, it should work out of the box.

**Comment by ZeiP** [comment]
I'm not, I've set Tracks up directly on my server. I think it's useful to support both approaches. Would it be possible to allow overriding the database credentials with another file, something like config/database.yml.local?

**Comment by mattr-** [comment]
Since I've started [adapting scripts-to-rule-them-all](https://github.com/github/scripts-to-rule-them-all) for this repo, I think we can make this work for both cases:
 - Re-add config/database.yml.tmpl to the repository
 - When a user runs `script/bootstrap` (which would need to be created), we could use that script to set up both `config/database.yml` and `config/site.yml` from their respective templates
 - Users who don't want to use the docker setup would just do this manually like normal (or we can figure out to make it work for both)

I don't have the bandwidth to tackle this immediately but would be happy to look at a PR.
