### ISSUE TITLE
Sponsoring development of the project

### ISSUE THREAD

**Issue by habernal** [TracksApp/tracks#2627]
I consider Tracks one of the most helpful productivity tools, been using that for many years now. Seeing the very slow development, few recent releases, etc., I was wondering whether sponsoring the project would help to keep the developers motivated. As an example, I'm sponsoring https://github.com/laurent22/joplin (also a great opensource tool) directly through github. Any thoughts?

(Edit: I'm self-hosting the app, so hosting subscription makes not much sense)

**Comment by ZeiP** [comment]
Thanks for the encouraging feedback! It's true that I've been quite busy in the spring because of other commitments, so Tracks development and for example creating a new release haven't gone forward as I would've hoped.

The hosting subscription is one way to support development. I've also now opened the possibility for donating via Github through my user profile: https://github.com/sponsors/ZeiP  Unfortunately the Finnish fundraising law doesn't allow for variable-sum sales, but if you can't find a sponsorship level you like let me know through email at zeip@getontracks.org and we can tailor one for you. Thanks for the great suggestion and for your positive feedback :)

**Comment by habernal** [comment]
Thanks @ZeiP for setting that up. To be honest, $10/month reaches the level of paid plans of similar commercial apps, which Tracks does not match in functionality (yet). I guess $5 would somehow be closer to what one gets as value for money. But it's an subjective opinion and I'm open to be convinced :)

**Comment by ZeiP** [comment]
Thanks for the feedback! I added another level of 5 USD / month with different perks. One way to contribute is also by subscribing to the hosted service (3 EUR / month) even if you aren't planning on using it. All support is very welcome and appreciated so it's entirely up to you and other people thinking about contributing :)  Thanks for the idea and your comments!

**Comment by habernal** [comment]
Done :)
