### ISSUE TITLE
Roadmap for new releases

### ISSUE THREAD

**Issue by habernal** [TracksApp/tracks#2678]
Dear all, there are few open bugs here and there, but the latest release (2.5.1) was published long time ago.

I would be great to setup a new release target (say 2.5.2), assign the bugs to that milestone, and release once fixed.

I've been donating to this project for some months now but have a feeling, it's dying slowly again (?)

**Comment by ZeiP** [comment]
Thanks for the request! Indeed it has been too long since the last release – I almost got it done in September, but then there was something like one thing pending after that and since then I've been quite busy with my day job. Sorry for that!

The issues that should be fixed before the next release should be present in the project board (https://github.com/TracksApp/tracks/projects/3), but right now I think there's some issue missing. I'll check the configuration in order to fully update that board as a roadmap for the next release, if there are any issues besides the listed ones pending. Hopefully I'll get a release out soon!
