### ISSUE TITLE
Change project description field to 'Succesful Outcome", make it larger and mandatory.

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#565]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/565_

BSAG

hey, putting in my projects, and I notice that you have a dinky little description box, I feel it would be better used, and more GTD centric to use this space as a Successful Outcome box, and make it mandatory (or option to set it mandatory). Thereby requiring more GTD based thinking in creating projects. 

_Originally reported by Anonymous on September 9, 2007 at 01:13:14 (-0400)_

**Comment by tmueller78** [comment]
Making it mandatory would automatically make all next actions associated with a project, but a significant portion of next actions are just that - next actions without a project.
Therefore in GTD thinking, this would actually be a step back.

**Comment by dnrce** [comment]
@tmueller78, this suggestion is to make "description" a mandatory field for new projects, not to make "project" a mandatory field for new actions

**Comment by tmueller78** [comment]
Sorry, I skimmed all open issues to check whether mine did exist already, and I obviously didn't read this one close enough. 
Still, I don't consider it a useful mandatory field because the desired outcome should be immediately known by reading the title, ideally with a past verb (e.g. "winter tires mounted"). 
An addtional description should not be necessary for the user himself unless it's a special case (e.g. write down some project reference information) - else something is wrong with your GTD practice anyway. I'm a certified GTD trainer, so I known what I'm saying... :)
