### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#682]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/682_

Does Tracks support encryption at present? If not, are the any unofficial hacks that people who need it resort to, such as using a different HTTP server, and are there plans to implement it? 

I reckon it'd be a pretty important feature; I wouldn't want the entire world to be able to sniff my traffic and learn what I'm up to.

_Originally reported by Anonymous on March 3, 2008 at 02:20:57 (-0700)_

**Comment by tmueller78** [comment]
I second this. Also, I think the text in the database should be at least encypted by something simple like ROT13 (http://en.wikipedia.org/wiki/ROT13). In order to allow other users to use one's installation, this would at least get rid of the other user's concern that one can read the data in plain text in the database.

**Comment by dnrce** [comment]
@tmueller78, encryption of the database would be a separate issue (but not a good approach to data privacy).

**Comment by mattr-** [comment]
SSL is going to be as good as it gets for encryption based things at the moment, which is already possible to do. Closing.
